// Generated by `./workspace bootstrap` and `./workspace render` from
// .workspace/workspace.json. Do not hand-edit: add a person to workspace.json
// and re-render.
//
// This module is the reason no template contains a person's name. The source
// vault hardcoded a two-name suggester in three templates, which is the single
// line that made those templates unforkable.
module.exports = {
  list: () => [
    { key: "{{PRIMARY_OPERATOR_KEY}}", display: "{{PRIMARY_OPERATOR}}", default: true }
  ],

  // One operator: no prompt, because there is no choice to make.
  // Two or more: one suggester. The switch flips on count, so adding a person
  // changes this file and nothing else.
  pick: async (tp, label) => {
    const ops = module.exports.list();
    if (ops.length === 1) return ops[0];
    const fallback = ops.find((o) => o.default) || ops[0];
    const chosen = await tp.system.suggester(
      ops.map((o) => o.display), ops, false, label || "Which operator?"
    );
    return chosen || fallback;
  },

  // Vault-relative personal workspace path for an operator.
  home: (op) => `Operators/${op.key}`,
};
